### ISSUE TITLE
Chrome on Win10 blocks Crycker 1.1

### ISSUE THREAD

**Issue by jadbox** [davidvidmar/Crycker#26] opened 2020-06-27 13:05 UTC
Chrome says: "Crycker.exe" is dangerous so Chrome has blocked it.

Chrome: 83.0.4103.116

**Comment by ghost** [comment] 2020-07-05 13:14
Firefox too.

**Comment by davidvidmar** [comment] 2020-07-23 20:08
Looking into this. Freshly compiled version on two (clean) computers result in same binary, but still VirusTotal reports infections.

**Comment by davidvidmar** [comment] 2021-03-25 07:42
I'll close this as a Duplicate of #27. I'll report the progress there.

**Closed as completed by davidvidmar** 2021-03-25 07:42 UTC
Labels: working-on
